// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApwaLUgG-vqviq1mBfHRleb4HKb1qbq-M',
    appId: '1:855394379832:web:dcbe4c4cfd053004a8decd',
    messagingSenderId: '855394379832',
    projectId: 'chat-app-a2159',
    authDomain: 'chat-app-a2159.firebaseapp.com',
    storageBucket: 'chat-app-a2159.appspot.com',
    measurementId: 'G-4CD93RKWY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGEwTqZ8vdCRmyMtWePZUCs51xGgU7tPM',
    appId: '1:855394379832:android:cf9c65a66b7e955fa8decd',
    messagingSenderId: '855394379832',
    projectId: 'chat-app-a2159',
    storageBucket: 'chat-app-a2159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQiemnVgdtqsnpGCOmyo_tPkA5TSoyIU',
    appId: '1:855394379832:ios:2de34e8c6e6d980ba8decd',
    messagingSenderId: '855394379832',
    projectId: 'chat-app-a2159',
    storageBucket: 'chat-app-a2159.appspot.com',
    iosClientId: '855394379832-7qv12q6jt83mtgocp231lglhv2sg8uo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
